Repository NCATComp410/comp410_spring_2022, pull requests merged in 2022-03, with the labels that each got.

#125 Sprint2
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#119 Implemented has_email() and has_ssn()
  pii_data.py
  test_pii_data.py
Labels: Megaminds

#109 Implemented has_email() function and pii_test
  pii_data.py
  sample_data.txt
  test_pii_data.py
Labels: T1

#130 Added has_name() and has_ipv4(), with testing
  pii_data.py
  test_pii_data.py
Labels: T1

#132 Implement has_street_address
  pii_data.py
  sample_data.txt
  test_pii_data.py
Labels: Bug Smashers

#113 Adding code for credit card and @ handle
  pii_data.py
  test_pii_data.py
Labels: Megaminds

#127 Address
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#150 Implement has_at_handle and has_credit_card as well as tests for both
  pii_data.py
  test_pii_data.py
Labels: T1

#146 Testing phone number code
  pii_data.py
  test_pii_data.py
Labels: Megaminds

#134 finished has at_handle
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#145 Bugsmasher email & at handle
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#152 Sprint2
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#153 Implemented has_ipv6 function
  pii_data.py
  test_pii_data.py
Labels: T1

#154 implemented has_street_address
  pii_data.py
  test_pii_data.py
Labels: T1

#156 added has_ssn function
  pii_data.py
Labels: T1

#158 Implemented has_credit_card function
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#163 Implemented at_handle
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#167 Completed credicard
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#168 Completed Anonymize Phone number
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#169 Completed ssn anonymize
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#170 Added emails test back
  test_pii_data.py
Labels: Wall-E
