Repository NCATComp410/comp410_spring_2022, pull requests merged in 2022-04, with the labels that each got.

#178 Implemented IPv4 and IPv6 anonymize functions.
  pii_data.py
  test_pii_data.py
Labels: Megaminds

#180 anonymize ipv4
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#181 S3 street address
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#172 at-handle
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#187 S3 name
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#162 implement anonymize function for iPv4
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#200 Sprint 3
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#193 adding has_name and has_street_address anonymize
  pii_data.py
  test_pii_data.py
Labels: Megaminds

#199 a
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#198 anonymize ipv4
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#197 Anon address
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#196 Added anonymize name
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#204 Anonymized name and ipv4
  pii_data.py
  test_pii_data.py
Labels: T1

#205 Implemented anonymity support
  pii_data.py
  test_pii_data.py
Labels: T1

#202 Sprint 3 anonymized name and address
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#210 Anonymize phone number
  pii_data.py
  test_pii_data.py
Labels: Megaminds

#213 Wall e Anonymized Email Address
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#207 Phone num anon
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#215 Larry local branch
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#218 Anonymize Credit card
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#217 Sprinthree anonymize ssn
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#221 sp3 ipv6
  pii_data.py
  test_pii_data.py
Labels: T1

#222 Sprint 3 anonymize credit card
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#220 Sp3 has streetaddress
  pii_data.py
  test_pii_data.py
Labels: T1

#224 Implemented Anonymize _ssn. Updated _ssn test cases
  pii_data.py
  test_pii_data.py
Labels: T1

#233 PII leak
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#234 PII Leak
  .gitignore
  pii_data.py
  test_pii_data.py
Labels: Megaminds
