Repository NCATComp410/comp410_spring_2022, pull requests merged in 2022-02, with the labels that each got.

#37 Added slogan
  sample_data.txt
  test_pii_data.py
Labels: Bug Smashers

#43 Implemmented my sologan
  sample_data.txt
  test_pii_data.py
Labels: Megaminds

#69 Implemented has_ipv4() method and create test cases
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#70 commented out test case for embedded to avoid testing issues for rest of the team
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#90 Implemented has_name function
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#78 Completed has_CC, has_phone, has_SSN
  pii_data.py
  sample_data.txt
  test_pii_data.py
Labels: Wall-E

#97 sprint2 us phone number pull request
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#94 Implemented IPv4 fixed
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#91 Bugsmasher email
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#100 Wall e has_email function
  pii_data.py
  test_pii_data.py
Labels: Wall-E

#102 Added has_CC
  pii_data.py
  test_pii_data.py
Labels: Bug Smashers

#80 implement has_ipv6 method
  pii_data.py
  test_pii_data.py
Labels: Code-Repeat

#105 Adding IPv4 and IPv6 functions.
  pii_data.py
  test_pii_data.py
Labels: Megaminds

#115 sprint 2 completed
  pii_data.py
  sample_data.txt
  test_pii_data.py
Labels: Code-Repeat

#116 Added Amex case
  pii_data.py
  test_pii_data.py
Labels: Wall-E
